name: repo_viewer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.3.0
  auto_route_generator: ^2.1.0
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  flash: ^2.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_secure_storage: ^4.2.1
  freezed_annotation: ^0.14.2
  hooks_riverpod: ^1.0.0-dev.6
  oauth2: ^2.0.0
  webview_flutter: ^2.0.12

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  lint: ^1.5.3

flutter:
  uses-material-design: true
  